spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto # manual X auto O
        retry:
          enabled: true # 재시도
          initial-interval: 1s # 최초 메시지 처리 실패 후 재시도까지의 인터벌
          max-interval: 3s # 최대 재시도 인터벌
          max-attempts: 2 # 최대 재시도 횟수

